language: python
before_install:
- sudo add-apt-repository --yes ppa:fontforge/fontforge
- sudo apt-get update -qq
- sudo apt-get install python-fontforge
- cp /usr/lib/python2.7/dist-packages/fontforge.* "$HOME/virtualenv/python2.7.8/lib/python2.7/site-packages"
install:
- pip install git+https://github.com/behdad/fontTools.git
- pip install git+https://github.com/googlefonts/fontbakery-cli.git
- pip install jinja2
script: PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery.py .
branches:
  only:
  - master
after_script:
- rm -rf builds/build/sources builds/build/build.state.yaml
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH bakery-report.py builds/build
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH travis-deploy.py
env:
  global:
    secure: RohGk1xY8pvcCcApJPGYD/I5qdY9hjjTebyauVg9Ehcsy6pzoudWE0XV1g9o8b5ApyTqjtrjDm+W3eQE/bX8w7/kdxz7hLC+J+YNMIYjGwQ8h6Z/dmvziY6PhC54YQuW9iS8/oiqTJ0Yu9AkJaHgG4vHLYpUaM7oX37uEtL4ceY=
